.\" Manpage for bajoo.
.\" Contact support@bajoo.fr to correct errors or typos.
.TH man 1 "15 May 2016" "1.0" "bajoo man page"
.SH NAME
bajoo \- start the bajoo application
.SH SYNOPSIS
bajoo
.SH DESCRIPTION
 Official client for the cloud storage service Bajoo.

 Bajoo is a service which lets you store your files in the cloud, and share them
 into multiples devices and multiples users.
 All files are encrypted client-side (before being sent to the bajoo servers)
 with your secret phrase you're the only one to know.

 This client is a graphic program aimed to interact with the bajoo service. It
 can synchronize local folders with files stored in the Bajoo cloud.

 For more details, see https://www.bajoo.fr
.SH OPTIONS
The bajoo application does not take any options.
.SH BUGS
No known bugs.
.SH AUTHOR
Bajoo Dev Team (support@bajoo.fr)
